# Generated by Django 5.0.6 on 2025-03-14 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_employee_facility_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'position': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_departments', to='main.employee'),
        ),
    ]
